# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-DaC-Reference
  description: Buildkite Pipeline for DaC-Reference
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/DaC-Reference

spec:
  type: buildkite-pipeline
  owner: group:threat-research-and-detection-engineering
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: DaC-Reference
      description: 
    spec:
      repository: elastic/DaC-Reference
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        threat-research-and-detection-engineering:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
