# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DaC-Reference
  description: DaC Repo to store the reference documentation and detection-rules management with Elastic rules
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/DaC-Reference
  annotations:
    backstage.io/source-location: "url:https://github.com/elastic/DaC-Reference/"
    github.com/project-slug: "elastic/DaC-Reference"
    github.com/team-slug: "elastic/threat-research-and-detection-engineering"
    buildkite.com/project-slug: "elastic/DaC-Reference"

spec:
  type: service
  owner: group:threat-research-and-detection-engineering
  lifecycle: production
